name: create and publish docker image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: .json to env
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: '.json'

      - name: github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: qemu
        uses: docker/setup-qemu-action@v3.2.0

      - name: buildx
        uses: docker/setup-buildx-action@v3

      - name: build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: arch.dockerfile
          push: true
          sbom: true
          provenance: mode=max
          platforms: linux/amd64,linux/arm64
          build-args: |
            APP_NAME=${{ env.json_name }}
            APP_VERSION=${{ env.json_version }}
          tags: |
            ${{ env.json_image }}:${{ env.json_version }}
            ${{ env.json_image }}:stable
            ghcr.io/${{ env.json_image }}:${{ env.json_version }}
            ghcr.io/${{ env.json_image }}:stable
