name: create and publish docker image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: image name
        run: echo "IMAGE_NAME=$(jq -r '.image' .json)" >> $GITHUB_ENV

      - name: app version
        run: echo "APP_VERSION=$(jq -r '.version' .json)" >> $GITHUB_ENV

      - name: github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: qemu
        uses: docker/setup-qemu-action@v3.2.0

      - name: buildx
        uses: docker/setup-buildx-action@v3

      - name: build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: arch.dockerfile
          push: true
          sbom: true
          provenance: mode=max
          platforms: linux/amd64,linux/arm64
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.APP_VERSION }}
            ${{ env.IMAGE_NAME }}:stable
            ghcr.io/${{ env.IMAGE_NAME }}:${{ env.APP_VERSION }}
            ghcr.io/${{ env.IMAGE_NAME }}:stable
