name: create and publish docker image

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: app version
        run: echo "APP_VERSION=$(jq -r '.version' .json)" >> $GITHUB_ENV

      - name: github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: eqmu
        uses: docker/setup-qemu-action@v3.2.0

      - name: buildx
        uses: docker/setup-buildx-action@v3

      - name: build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: arch.dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
          tags: |
            ${{ github.repository }}:${{ env.APP_VERSION }}
            ${{ github.repository }}:stable
            ghcr.io/${{ github.repository }}:${{ env.APP_VERSION }}
            ghcr.io/${{ github.repository }}:stable
