name: tags
on:
  push:
    tags:
      - 'v*'
jobs:
  tags:
    runs-on: ubuntu-latest
    steps:
      - name: init / checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: tags
        id: commit
        run: |
          echo "current tag: ${{ github.ref_name }}"
          git rev-list --tags
          git tag

          LOCAL_COMMITS=$(git log v0.1.6..HEAD --oneline)
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "history<<${EOF}" >> ${GITHUB_OUTPUT}
          echo "${LOCAL_COMMITS}" >> ${GITHUB_OUTPUT}
          echo "${EOF}" >> ${GITHUB_OUTPUT}

      - name: check output
        run: |
          echo ${{ steps.commit.outputs.history }}