name: tags
on:
  push:
    tags:
      - 'v*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: init / checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ github.ref }}

      - name: tags
        run: |
          git log ${{ github.ref }}..HEAD --oneline

      - name: build docker image
        uses: the-actions-org/workflow-dispatch@3133c5d135c7dbe4be4f9793872b6ef331b53bc7
        with:
          workflow: dev.yml
          wait-for-completion: false
          token: "${{ secrets.REPOSITORY_TOKEN }}"