name: tags
on:
  push:
    tags:
      - 'v*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: create dynamic README.md
        run: |
          echo -e "# Foo\nHello Bar!" > README.md
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git commit -am "dynamic readme"
          git push