name: tags
on:
  push:
    tags:
      - 'v*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: init / checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: tags
        run: |
          LOCAL_LAST_COMMIT=$(git rev-list --tags --skip=1 --max-count=1)
          LOCAL_LAST_TAG=$(git describe --abbrev=0 --tags ${LOCAL_LAST_COMMIT})
          echo "last commit hash: ${LOCAL_LAST_COMMIT}"
          echo "last tag before ${{ github.ref_name }} was: ${LOCAL_LAST_TAG}"

          LOCAL_COMMITS=$(git log ${LOCAL_LAST_TAG}..HEAD --oneline)
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "commits<<${EOF}" >> ${GITHUB_OUTPUT}
          echo "${LOCAL_COMMITS}" >> ${GITHUB_OUTPUT}
          echo "${EOF}" >> ${GITHUB_OUTPUT}