name: tags
on:
  push:
    tags:
      - 'v*'
jobs:
  tags:
    runs-on: ubuntu-latest
    steps:
      - name: init / checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: main

      - name: tags
        id: commit
        run: |
          echo "current tag: ${{ github.ref_name }}"
          echo "tag -1: $(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)"
          echo "tag -2: $(git describe --abbrev=0 --tags `git rev-list --tags --skip=2 --max-count=1`)"
          echo "tag -3: $(git describe --abbrev=0 --tags `git rev-list --tags --skip=3 --max-count=1`)"

          LOCAL_COMMITS=$(git log v0.1.6..HEAD --oneline)
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "history<<${EOF}" >> ${GITHUB_OUTPUT}
          echo "${LOCAL_COMMITS}" >> ${GITHUB_OUTPUT}
          echo "${EOF}" >> ${GITHUB_OUTPUT}

      - name: check output
        run: |
          echo ${{ steps.commit.outputs.history }}